### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mrayson** [iosonobert/pIMOS#11]
List of items for @sherry-fang (@iosonobert, @williamedge  please add):

- [ ] Make pip installable
- [ ] Create sphinx docs with api and example
- [ ] doc strings (required for above)
- [ ] unit tests

**Comment by iosonobert** [comment]
Note the code we have actually used to run full field trips is here https://github.com/iosonobert/pimos-uwa
